name: Python application

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  
        pip install -r requirements.txt  

    - name: Run tests
      run: |
        python -m unittest test_meu_projeto.py  

    - name: Package project
      run: zip -r meu_projeto.zip .  # Compacta o projeto em um arquivo ZIP.

    - name: Upload artifact
      uses: actions/upload-artifact@v3  # Envia o arquivo ZIP como artefato.
      with:
        name: meu_projeto-artifact  # Nome do artefato.
        path: meu_projeto.zip  # Caminho do arquivo ZIP que será enviado.
