name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ' 3.13.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check environment variables
      run: |
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        echo "Listing installed packages:"
        pip list

    - name: Run tests
      run: |
        python -m unittest test_conversao.py

    - name: Package project
      run: zip -r conversao.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: conversao-artifact
        path: conversao.zip
